[build]
builder = "DOCKERFILE"
dockerfilePath = "whatsapp-bridge/Dockerfile"

[deploy]
startCommand = "./main"
healthcheckPath = "/api/chats"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8080" 