[build]
builder = "DOCKERFILE"
dockerfilePath = "whatsapp-bridge/Dockerfile"

[deploy]
startCommand = "./whatsapp-bridge"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8080" 