[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/whatsapp-bridge"
healthcheckPath = "/api/status"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
PORT = "8080"
STORE_PATH = "/data/store"
STORE_PERMISSIONS = "777"
DEBUG = "true"