[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./whatsapp-bridge"
healthcheckPath = "/api/status"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"
STORE_PATH = "/data/store"
STORE_PERMISSIONS = "777"