[build]
builder = "DOCKERFILE"
dockerfilePath = "api-server/Dockerfile"
buildPath = "api-server"

[deploy]
startCommand = "./main"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 