[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.api"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 